# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TourOfHeroes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TourOfHeroes
  pod 'RealmSwift'
  pod 'Alamofire', '~> 5.2'
  pod 'IQKeyboardManagerSwift', '6.5.6'
  pod 'Nuke', '~> 9.0'
  pod "SkeletonView"
  pod 'NamadaLayout', '2.0.1-beta' 

  target 'TourOfHeroesTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'TourOfHeroesUITests' do
    # Pods for testing
  end

end
